# Use docker-based build environment (instead of openvz)
sudo: false

language: java
jdk:
  - oraclejdk8
#pending skip artifact deployment:  - openjdk7

addons:
  postgresql: "9.3"

env:
  global:
    # Credentials to deploy to Maven Artifacts
    - secure: Q0LjGCaS2LIB0z1XH1Qx4uAmGgG9mIlsZAtdSGbgd4XwRbWM5zPxaRtoe5YJCt4zeAOu9+TYxpqa5kv5EyizY0zSC8dEZQu6Ur7jfre2FaJ9O0sSq72Cn2cTVVXTEQi+CPnaK/pki/NpDSN6Zt82n7ypgxZOInFT+BtcXDK8ok0=
    - secure: Z6o9+yl9my8JeXolPQStUKLlImmLOfagRlFLFN4uSXWQ2SVP4dVhzZGB+2bVCNSmLuQqV0CRbALkOF0f8cHi+qGiwTKqIwcp1d2BUqASP6oGHH/PtuspOsYoV4NzsQ86CCpI3Kakt2C7gDRv/0ES/Qw0Vjc/Ob21Hj3zeJ9amXo=

before_script:
  - mysql -e 'create database testdatabase;'
  - psql -c 'create database testdatabase;' -U postgres

# Build everything in 'script' phase
install: /bin/true

script:
  # pending: optimize clean/test steps
#  - mvn clean install -B -Dintegration_test_settings=`pwd`/test/travis-ci/components-persistence-hsql.properties
  - mvn clean install -B -Dintegration_test_settings=`pwd`/test/travis-ci/components-persistence-mysql.properties
#  - mvn clean install -B -Dintegration_test_settings=`pwd`/test/travis-ci/components-persistence-postgresql.properties

  # Deploy built artifacts
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn deploy -Dintegration_test_settings=`pwd`/test/travis-ci/components-persistence-mysql.properties -B --settings test/travis-ci/settings.xml ; fi

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura

notifications:
  webhooks:
    urls:
      - secure: BIFGDLML5oxcSqmLajNlylkIKpTYR9yhkL9tWT82w8WqKDYOZxRfjnRtE8gmP+aREawrhr2dwnA+/WCc5/UMIerib22GAj65GymVgesw543zYDDDYSiJIIxu7EsAfTv34ayibn7rsHcaoiGsS1rge0CGzFivs48Ra3ZUcR907HA=
    on_success: always
    on_failure: always

cache:
  directories:
    - '$HOME/.m2/repository'
